let calculate_entropy y = ()
let mean_squared_error y_true y_pred = ()
let distance x1 x2 = ()
let accuracy y_true y_pred = ()
let normalize x = ()
let split x y test_percent cross_val_percent = ()
let one_hot_of_nominal x = ()
let nominal_of_one_hot x = ()
let turn_vector_to_diagonal_matrix x = ()

(* Utils specific to SVMs: *)
let linear_kernel = ()
let polynomial_kernel power coef = ()
let rbf_kernel gamma = ()